import type { DashboardSeed, Persona } from "@/lib/types";

export const personas: Persona[] = [
  {
    key: "visitor",
    name: "Visiteur public",
    role: "public",
    goal: "Comprendre la plateforme, consulter les ressources et creer un compte.",
    workflow: "Consulte annuaires, offres, formations, articles, newsletter.",
    cta: "Explorer la V0",
    href: "/",
  },
  {
    key: "company",
    name: "Societe de nettoyage",
    role: "company_owner",
    goal: "Se rendre visible, recruter, proposer une formation et demander l'association.",
    workflow: "Fiche societe, job board, formations, adhesion association.",
    cta: "Voir les societes",
    href: "/annuaire/societes",
  },
  {
    key: "supplier",
    name: "Fournisseur",
    role: "supplier_owner",
    goal: "Referencer gratuitement ses produits et services.",
    workflow: "Fiche fournisseur, categories, validation admin.",
    cta: "Voir les fournisseurs",
    href: "/annuaire/fournisseurs",
  },
  {
    key: "independent",
    name: "Independant / sous-traitant",
    role: "independent_profile",
    goal: "Valoriser ses competences et acceder aux missions privees apres validation.",
    workflow: "Profil, demande association, candidatures missions.",
    cta: "Voir les independants",
    href: "/independants",
  },
  {
    key: "candidate",
    name: "Candidat emploi",
    role: "candidate_profile",
    goal: "Creer un profil, candidater et suivre ses candidatures.",
    workflow: "Profil candidat, offres, candidature, suivi.",
    cta: "Voir les candidats",
    href: "/candidats",
  },
  {
    key: "training",
    name: "Organisme de formation",
    role: "training_organization",
    goal: "Referencer des formations et recevoir des demandes qualifiees.",
    workflow: "Fiche organisme, formations, sessions, validation admin.",
    cta: "Voir les formations",
    href: "/formations",
  },
  {
    key: "trainer",
    name: "Chef d'entreprise formateur",
    role: "company_owner",
    goal: "Publier une formation terrain depuis un compte entreprise.",
    workflow: "Compte societe, formation pratique, validation admin.",
    cta: "Proposer une formation",
    href: "/formations",
  },
  {
    key: "author",
    name: "Auteur / redacteur",
    role: "author",
    goal: "Creer des guides et ressources pour alimenter le SEO sectoriel.",
    workflow: "Brouillon article, revue admin, publication.",
    cta: "Voir les ressources",
    href: "/ressources",
  },
  {
    key: "admin",
    name: "Admin / super admin",
    role: "admin",
    goal: "Valider, moderer, exporter et garantir la qualite des donnees.",
    workflow: "Back-office, statuts, moderation, badges.",
    cta: "Ouvrir l'admin",
    href: "/admin",
  },
];

export const dashboards: DashboardSeed[] = [
  {
    role: "company_owner",
    label: "Dashboard societe",
    summary: "Piloter fiche entreprise, offres, formations et adhesion association.",
    actions: ["Completer la fiche", "Publier une offre", "Demander l'association", "Proposer une formation"],
    metrics: [
      { label: "Score profil", value: "82%" },
      { label: "Candidatures", value: "4" },
      { label: "Statut association", value: "Validee" },
    ],
  },
  {
    role: "supplier_owner",
    label: "Dashboard fournisseur",
    summary: "Gerer fiche fournisseur, categories, demandes et validation.",
    actions: ["Completer la fiche", "Ajouter un service", "Verifier la couverture"],
    metrics: [
      { label: "Statut fiche", value: "En attente" },
      { label: "Categories", value: "2" },
      { label: "Leads", value: "0" },
    ],
  },
  {
    role: "independent_profile",
    label: "Dashboard independant",
    summary: "Valoriser competences, disponibilite et acces association.",
    actions: ["Completer le profil", "Demander l'association", "Voir missions privees"],
    metrics: [
      { label: "Score profil", value: "76%" },
      { label: "Statut association", value: "Soumise" },
      { label: "Missions", value: "Reservees" },
    ],
  },
  {
    role: "candidate_profile",
    label: "Dashboard candidat",
    summary: "Suivre profil, candidatures, disponibilite et formations utiles.",
    actions: ["Ajouter un CV", "Postuler", "Consulter formations"],
    metrics: [
      { label: "Candidatures", value: "1" },
      { label: "Disponibilite", value: "Immediate" },
      { label: "Profil", value: "68%" },
    ],
  },
  {
    role: "admin",
    label: "Dashboard admin",
    summary: "Valider, moderer et surveiller la qualite des donnees.",
    actions: ["Valider profils", "Moderation contenus", "Exporter CSV", "Gerer badges"],
    metrics: [
      { label: "En attente", value: "7" },
      { label: "Membres", value: "1" },
      { label: "Missions", value: "2" },
    ],
  },
];
