import type { DashboardSeed, Persona } from "@/lib/types";

export const personas: Persona[] = [
  {
    key: "visitor",
    name: "Visiteur public",
    role: "public",
    goal: "Comprendre la plateforme, consulter les ressources et créer un compte.",
    workflow: "Consulte annuaires, offres, formations, articles, newsletter.",
    cta: "Explorer la V0",
    href: "/",
  },
  {
    key: "company",
    name: "Société de nettoyage",
    role: "company_owner",
    goal: "Se rendre visible, recruter, proposer une formation et demander l'association.",
    workflow: "Fiche société, job board, formations, adhésion association.",
    cta: "Voir les sociétés",
    href: "/annuaire/societes",
  },
  {
    key: "supplier",
    name: "Fournisseur",
    role: "supplier_owner",
    goal: "Référencer gratuitement ses produits et services.",
    workflow: "Fiche fournisseur, catégories, validation admin.",
    cta: "Voir les fournisseurs",
    href: "/annuaire/fournisseurs",
  },
  {
    key: "independent",
    name: "Indépendant / sous-traitant",
    role: "independent_profile",
    goal: "Valoriser ses compétences et accéder aux missions privées après validation.",
    workflow: "Profil, demande association, candidatures missions.",
    cta: "Voir les indépendants",
    href: "/independants",
  },
  {
    key: "candidate",
    name: "Candidat emploi",
    role: "candidate_profile",
    goal: "Créer un profil, candidater et suivre ses candidatures.",
    workflow: "Profil candidat, offres, candidature, suivi.",
    cta: "Voir les candidats",
    href: "/candidats",
  },
  {
    key: "training",
    name: "Organisme de formation",
    role: "training_organization",
    goal: "Référencer des formations et recevoir des demandes qualifiées.",
    workflow: "Fiche organisme, formations, sessions, validation admin.",
    cta: "Voir les formations",
    href: "/formations",
  },
  {
    key: "trainer",
    name: "Chef d'entreprise formateur",
    role: "company_owner",
    goal: "Publier une formation terrain depuis un compte entreprise.",
    workflow: "Compte société, formation pratique, validation admin.",
    cta: "Proposer une formation",
    href: "/formations",
  },
  {
    key: "author",
    name: "Auteur / rédacteur",
    role: "author",
    goal: "Créer des guides et ressources pour alimenter le SEO sectoriel.",
    workflow: "Brouillon article, revue admin, publication.",
    cta: "Voir les ressources",
    href: "/ressources",
  },
  {
    key: "admin",
    name: "Admin / super admin",
    role: "admin",
    goal: "Valider, modérer, exporter et garantir la qualité des données.",
    workflow: "Back-office, statuts, modération, badges.",
    cta: "Ouvrir l'admin",
    href: "/admin",
  },
];

export const dashboards: DashboardSeed[] = [
  {
    role: "company_owner",
    label: "Dashboard société",
    summary: "Piloter fiche entreprise, offres, formations et adhésion association.",
    actions: ["Compléter la fiche", "Publier une offre", "Demander l'association", "Proposer une formation"],
    metrics: [
      { label: "Score profil", value: "82%" },
      { label: "Candidatures", value: "4" },
      { label: "Statut association", value: "Validée" },
    ],
  },
  {
    role: "supplier_owner",
    label: "Dashboard fournisseur",
    summary: "Gérer fiche fournisseur, catégories, demandes et validation.",
    actions: ["Compléter la fiche", "Ajouter un service", "Vérifier la couverture"],
    metrics: [
      { label: "Statut fiche", value: "En attente" },
      { label: "Catégories", value: "2" },
      { label: "Leads", value: "0" },
    ],
  },
  {
    role: "independent_profile",
    label: "Dashboard indépendant",
    summary: "Valoriser compétences, disponibilité et accès association.",
    actions: ["Compléter le profil", "Demander l'association", "Voir missions privées"],
    metrics: [
      { label: "Score profil", value: "76%" },
      { label: "Statut association", value: "Soumise" },
      { label: "Missions", value: "Réservées" },
    ],
  },
  {
    role: "candidate_profile",
    label: "Dashboard candidat",
    summary: "Suivre profil, candidatures, disponibilité et formations utiles.",
    actions: ["Ajouter un CV", "Postuler", "Consulter formations"],
    metrics: [
      { label: "Candidatures", value: "1" },
      { label: "Disponibilité", value: "Immédiate" },
      { label: "Profil", value: "68%" },
    ],
  },
  {
    role: "admin",
    label: "Dashboard admin",
    summary: "Valider, modérer et surveiller la qualité des données.",
    actions: ["Valider profils", "Modération contenus", "Exporter CSV", "Gérer badges"],
    metrics: [
      { label: "En attente", value: "7" },
      { label: "Membres", value: "1" },
      { label: "Missions", value: "2" },
    ],
  },
  {
    role: "super_admin",
    label: "Dashboard super admin",
    summary: "Gestion globale de la plateforme : utilisateurs, admins, sécurité et stratégie.",
    actions: ["Gérer les utilisateurs", "Modération", "Exporter CSV", "Audit sécurité"],
    metrics: [
      { label: "En attente", value: "7" },
      { label: "Utilisateurs", value: "10" },
      { label: "Admins", value: "2" },
    ],
  },
];
